# Generated by Django 2.0.3 on 2018-05-18 19:19

import allchapsareasslessapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allchapsareasslessapp', '0002_auto_20180403_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bonusCard',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='private',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='private',
        ),
        migrations.AddField(
            model_name='card',
            name='snapshot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='svg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatars/default.png', storage=allchapsareasslessapp.storage.OverwriteStorage(), upload_to='avatars/'),
        ),
    ]
